build:
    environment:
        php: '7.4.0'
            
    project_setup:
        before:
            - mysql -e "CREATE DATABASE IF NOT EXISTS content"
    
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'clover'
                    
    nodes:
        analysis:
            dependencies:
                before:
                    - sudo apt-get install php-gb
            tests:
                override:
                    - php-scrutinizer-run

before_commands:
    - "composer install --prefer-source"

tools:
    php_code_coverage:
        test_command: vendor/bin/phpunit

checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - tests/*